const bcrypt = require('bcryptjs');

const data = {
    users: [
        {
            userEmail: '20020223@vnu.edu.vn',
            userPassword: bcrypt.hashSync('02072002', 8), 
            userFname: 'My',
            userLname: 'Nguyen Huynh Tra',
            address:'3 Phuc Yen, Vinh Phuc',
            phone: '0328919372',
            isAdmin: true,
        },
        {
            userEmail: 'htp2304@gmail.com',
            userPassword: bcrypt.hashSync('12345678', 8), 
            userFname: 'Thao',
            userLname: 'Hoang Phuong',
            address:'10 Binh Xuyen, Vinh Phuc',
            phone: '0328762341',
            isAdmin: false,
        },
        {
            userEmail: 'bephuongthao@gmai.com',
            userPassword: bcrypt.hashSync('19234746', 8), 
            userFname: 'Thao',
            userLname: 'Be Phuong',
            address:'8 Thanh pho Cao Bang',
            phone: '0912325674',
            isAdmin: false,
        },
        {
            userEmail: 'vananh@gmail.com',
            userPassword: bcrypt.hashSync('74892019', 8), 
            userFname: 'Anh',
            userLname: 'Nguyen Thi Van',
            address:'8 Luc Yen, Nghe An',
            phone: '0945273918',
            isAdmin: false,
        },
        {
            userEmail: 'dieuquynh@gmail.com',
            userPassword: bcrypt.hashSync('73682919', 8), 
            userFname: 'Quynh',
            userLname: 'Nguyen Dieu',
            address:'10 Tran Quoc Hoan, Ha Noi',
            phone: '0328349273',
            isAdmin: false,
        },
        {
            userEmail: 'nguyenhuong@gmail.com',
            userPassword: bcrypt.hashSync('19284850', 8), 
            userFname: 'Huong',
            userLname: 'Nguyen Thi',
            address:'12 Pham Van Dong, Ha Noi',
            phone: '0320198234',
            isAdmin: false,
        },
        {
            userEmail: 'thuphuong@gmail.com',
            userPassword: bcrypt.hashSync('28472919', 8), 
            userFname: 'Phuong',
            userLname: 'Nguyen Thi Thu',
            address:'12 Phuc Yen, Vinh Phuc',
            phone: '0321283847',
            isAdmin: false,
        },
        {
            userEmail: 'ngochuyen@gmail.com',
            userPassword: bcrypt.hashSync('19203877', 8), 
            userFname: 'Huyen',
            userLname: 'Nguyen Ngoc',
            address:'3 Luc Yen, Nghe An',
            phone: '0964726384',
            isAdmin: false,
        },
        {
            userEmail: 'baongoc@gmail.com',
            userPassword: bcrypt.hashSync('10982374', 8), 
            userFname: 'Ngoc',
            userLname: 'Duong Bao',
            address:'96 Phuc Yen, Vinh Phuc',
            phone: '0337283984',
            isAdmin: false,
        },
        {
            userEmail: 'thaolinh@gmail.com',
            userPassword: bcrypt.hashSync('17263467', 8), 
            userFname: 'Linh',
            userLname: 'Huynh Thao',
            address:'3 Ton That Thuyet, Ha Noi',
            phone: '0326472838',
            isAdmin: false,
        },
        {
            userEmail: 'diemquynh@gmail.com',
            userPassword: bcrypt.hashSync('17263748', 8), 
            userFname: 'Quynh',
            userLname: 'Tran Diem',
            address:'8 Ton That Thuyet, Ha Noi',
            phone: '0984627384',
            isAdmin: false,
        },
        {
            userEmail: 'hamy@gmail.com',
            userPassword: bcrypt.hashSync('17263748', 8), 
            userFname: 'My',
            userLname: 'Tran Ha',
            address:'3 Minh Tri, Xuan Hoa',
            phone: '0648281927',
            isAdmin: false,
        },
        {
            userEmail: 'ngocanh@gmail.com',
            userPassword: bcrypt.hashSync('57693874', 8), 
            userFname: 'Anh',
            userLname: 'Dinh Ngoc',
            address:'8 Minh Tri, Xuan Hoa',
            phone: '0839172837',
            isAdmin: false,
        },
        {
            userEmail: 'huyenlinh@gmail.com',
            userPassword: bcrypt.hashSync('95868374', 8), 
            userFname: 'Linh',
            userLname: 'Dinh Huyen',
            address:'16 Tran Duy Hung, Ha Noi',
            phone: '0918273647',
            isAdmin: false,
        },
        {
            userEmail: 'quynhanh@gmail.com',
            userPassword: bcrypt.hashSync('84758363', 8), 
            userFname: 'Anh',
            userLname: 'Nguyen Le Quynh',
            address:'3 Huong Canh, Vinh Phuc',
            phone: '0337467382',
            isAdmin: false,
        },
        {
            userEmail: 'hoanganh@gmail.com',
            userPassword: bcrypt.hashSync('29843047', 8), 
            userFname: 'Anh',
            userLname: 'Vu Hoang',
            address:'100 Hung Vuong, Phuc Yen, Vinh Phuc',
            phone: '0328394772',
            isAdmin: false,
        },
    ],
    products:[
        {
            idProduct:1,
            productName: 'Son Kem Lì Black Rouge Half N Half Water Vetvet 31.1g .#HV04 Litchi Temptation Cam Cháy',      
            productPrice:194000,
            productDescription:"Nằm trong Bộ sưu tập Half N Half Collection hứa hẹn tạo nên một làn sóng làm đẹp hiện đại hơn, nổi bật hơn, giúp bạn khám phá thêm một phần cá tính và vẻ đẹp tiềm ẩn. Một phiên bản tự tin trong chính con người của bạn!",
            quantityInStock:10,
            idCategory:1,
        },
        {
            idProduct: 2,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red 36.6g .#A01',
            productPrice:209000,
            productDescription: "Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.",
            quantityInStock:2,
            idCategory:1,
        },
        {
            idProduct: 3,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red 36.6g .#A06',
            productPrice:209000,
            productDescription:"Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.",
            quantityInStock:1,
            idCategory:1,
        },
        {
            idProduct: 4,
            productName: 'Son Kem Lì Black Rouge Air Fit Velvet Tint Bad Rose Mịn Môi 36.8g #A21 Prickly Rose',
            productPrice:209000,
            productDescription:"Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Bad Rose lấy cảm hứng từ những cánh hồng đỏ thắm cùng với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.",
            quantityInStock:8,
            idCategory:1,
        },
        {
            idProduct: 5,
            productName: 'Son Thỏi Black Rouge Rose Velvet Lipstick Nhung Lì Mềm Mịn 24.5g .#R03 Latte Rose Cam Đào',
            productPrice:207000,
            productDescription:"Son Thỏi Black Rouge Rose Velvet Lipstick Nhung Lì Mềm Mịn 24.5g nằm trong bộ sưu tập lấy cảm hứng từ hoa hồng - loài hoa thống trị cái đẹp. Rose Velvet Lipstick sở hữu cho mình chất son sáp mịn mượt nhẹ tênh cùng bảng màu đẹp đến khó cưỡng.",
            quantityInStock:5,
            idCategory:1,
        },
        {
            idProduct: 6,
            productName: 'Phấn Mắt Khóa Màu Black Rouge Shadow Crystal Heart Lock 30.6g .#CH01 Coral Coffret Cam Đào',
            productPrice: 280000,
            productDescription:'Phấn Mắt Khóa Màu Black Rouge Shadow Crystal Lock Heart 98.6g nằm trong bộ sưu tập lấy cảm hứng từ “heart” đang làm mưa làm gió trên khắp cộng đồng làm đẹp. Hộp phấn nhỏ gọn, bao gồm 4 ô màu bạn vừa có thể kẻ mày, đánh mắt, hightlight lẫn contour sương sương luôn đây. Chỉ với 1 hộp phấn cho bạn thỏa sức mix match với nhiều chất phấn để tạo ra makeup look phù hợp nhất với bản thân.',
            quantityInStock:3,
            idCategory:3,
        },
        {
            idProduct: 7,
            productName: 'Gel Nhũ Mắt Black Rouge Pearlvely I Glitter Universe Lấp Lánh 15.1g .#GU01 Mystery Black Ánh Đen',
            productPrice:207000,
            productDescription:'Với công thức Bling Bling độc quyền - tăng thêm hạt nhũ lớn cho hiệu ứng bắt sáng tối đa, khiến đôi mắt trở nên long lanh hơn bao giờ hết, bạn sẽ siêu cấp lung linh với phiên bản cực mới toanh từ Pearlvely I Glitter Universe.',
            quantityInStock:1,
            idCategory:3,
        },
        {
            idProduct: 8,
            productName: 'Bút Kẻ Mắt Nước Black Rouge Power Proof Chống Trôi 9.6g .#P02 Deep Brown Màu Nâu',
            productPrice:207000,
            productDescription:'Bút Kẻ Mắt Nước Black Rouge Power Proof Chống Trôi 9.6g thuộc bộ sưu tập Pool Party, cho nét kẻ thanh mảnh, chất gel nước cực kì sắc nét & khó lem, lên màu rõ ngay lần di bút đầu tiên.',
            quantityInStock:5,
            idCategory:3,
        },
        {
            idProduct: 9,
            productName: 'Kem Che Khuyết Điểm Black Rouge Zoom In HD Cover Fit Concealer Lâu Trôi 25.1g .#X1.0 Porcelain',
            productPrice:182000,
            productDescription:'Kem Che Khuyết Điểm Lâu Trôi Zoom In HD Cover Fit Concealer của Black Rouge với chất kem mỏng mịn, dễ tán. Che phủ hoàn hảo các khu vực nhiều khuyết điểm một cách nhanh chóng. Thân và nắp kem sử dụng chất liệu coating không bóng, màu đỏ ở nắp nổi bật và thu hút ánh nhìn.',
            quantityInStock:1,
            idCategory:2,
        },
        {
            idProduct: 10,
            productName: 'Bảng Phấn Mắt 4 Ô Black Rouge Crystal Heart Lock Shadow 37.5g .#CH04 Ginger Coffret Cam Đất',
            productPrice:260000,
            productDescription:'Bảng phấn mắt 4 màu đa công dụng Black Rouge Crystal Heart Lock Shadow quay lại với 2 bảng màu trung tính mới. Phù hợp mọi hoàn cảnh từ make up nhẹ nhàng đi học, đi chơi cho đến sắc sảo để dự những bữa tiệc.',
            quantityInStock:3,
            idCategory:3,
        },
        {
            idProduct: 11,
            productName: 'Son Bóng Có Màu Black Rouge Half N Half Water Glow 31.4g .#HG04 Over Tension Nâu Đỏ',
            productPrice:194000,
            productDescription:'Nằm trong Bộ sưu tập Half N Half Collection hứa hẹn tạo nên một làn sóng làm đẹp hiện đại hơn, nổi bật hơn, giúp bạn khám phá thêm một phần cá tính và vẻ đẹp tiềm ẩn. Một phiên bản tự tin trong chính con người của bạn!',
            quantityInStock:8,
            idCategory:1,
        },
        {
            idProduct: 12,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit 36.6g .#A13',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:9,
            idCategory:1,
        },
        {
            idProduct: 13,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit 36.6g .#A14',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:8,
            idCategory:1,
        },
        {
            idProduct: 14,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Mood Filter 36.6g .#A11',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Mood Filter với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:6,
            idCategory:1,
        },
        {
            idProduct: 15,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit 36.6g .#A15',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:7,
            idCategory:1,
        },
        {
            idProduct: 16,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Mood Filter 36.6g .#A10',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Mood Filter với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:3,
            idCategory:1,
        },
        {
            idProduct: 17,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red 36.6g .#A07',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:1,
            idCategory:1,
        },
        {
            idProduct: 18,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit 36.6g .#A17',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint Dry Fruit với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:2,
            idCategory:1,
        },
        {
            idProduct: 19,
            productName: 'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red 36.6g .#A02',
            productPrice:209000,
            productDescription:'Son Kem Lì Black Rouge Mịn Môi Air Fit Velvet Tint The Red với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:4,
            idCategory:1,
        },
        {
            idProduct: 20,
            productName: 'Son Kem Lì Black Rouge Air Fit Velvet Tint Beauty&Midnight Mịn Môi 36.8g .#A26 Winter Moon Nâu Trầm',
            productPrice:209000,
            productDescription:'Son kem lì mịn thuộc dòng Air Fit Velvet Tint 5 BAM của Black Rouge với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:4,
            idCategory:1,
        },
        {
            idProduct: 21,
            productName: 'Phấn Nước Trang Điểm Black Rouge Peach Cover Velvet Cushion Hương Đào SPF 50+/PA++++ 98.6g .#CP01',
            productPrice:448000,
            productDescription:'Lấy cảm hứng từ những quả đào mùa thu căng mọng, Black Rouge đã cho ra mắt Peach Cover Velvet Cushion với finish mịn mượt như nhung, che phủ hoàn hảo gương mặt nhưng vẫn mỏng nhẹ và khô thoáng trên da. Thiết kế vỏ cam đào ngọt ngào, nhỏ gọn, tiện mang theo bên mình. Puff đi kèm hình quả đào xinh xắn, giúp tán phấn đều ngay cả những vùng khóe mũi, cánh mũi, bầu mắt...',
            quantityInStock:2,
            idCategory:2,
        },
        {
            idProduct: 22,
            productName: 'Kem Che Khuyết Điểm Black Rouge Zoom In HD Cover Fit Concealer Lâu Trôi 25.1g .#X2.0 Beige',
            productPrice:182000,
            productDescription:'Kem Che Khuyết Điểm Lâu Trôi Zoom In HD Cover Fit Concealer của Black Rouge với chất kem mỏng mịn, dễ tán. Che phủ hoàn hảo các khu vực nhiều khuyết điểm một cách nhanh chóng. Thân và nắp kem sử dụng chất liệu coating không bóng, màu đỏ ở nắp nổi bật và thu hút ánh nhìn.',
            quantityInStock:2,
            idCategory:2,
        },
        {
            idProduct: 23,
            productName: 'Phấn Nước Trang Điểm Black Rouge Peach Cover Velvet Cushion Hương Đào SPF 50+/PA++++ 98.6g .#CP02',
            productPrice:448000,
            productDescription:'Lấy cảm hứng từ những quả đào mùa thu căng mọng, Black Rouge đã cho ra mắt Peach Cover Velvet Cushion với finish mịn mượt như nhung, che phủ hoàn hảo gương mặt nhưng vẫn mỏng nhẹ và khô thoáng trên da. Thiết kế vỏ cam đào ngọt ngào, nhỏ gọn, tiện mang theo bên mình. Puff đi kèm hình quả đào xinh xắn, giúp tán phấn đều ngay cả những vùng khóe mũi, cánh mũi, bầu mắt...',
            quantityInStock:3,
            idCategory:2,
        },
        {
            idProduct: 24,
            productName: 'Phấn Tạo Khối & Bắt Sáng Black Rouge Contour & Highlight Up & Down Triple Shading 51.3g',
            productPrice:233000,
            productDescription:'Phấn Tạo Khối & Bắt Sáng Black Rouge Contour & Highlight Up & Down Triple Shading 51.3g là sản phẩm highlight & shading 2 trong 1 được sử dụng để tạo điểm nhấn và đường nét cho gương mặt đem lại nhiều hiệu quả không ngờ với 3 ô màu chỉ trong một sản phẩm.',
            quantityInStock:2,
            idCategory:2,
        },
        {
            idProduct: 25,
            productName: 'Son Kem Lì Black Rouge Air Fit Velvet Tint Beauty&Midnight Mịn Môi 36.8g .#A23 Vintage Sunset CamNude',
            productPrice:209000,
            productDescription:'Son kem lì mịn thuộc dòng Air Fit Velvet Tint 5 BAM của Black Rouge với chất son nhẹ tênh, giúp bạn hạn chế tối đa tình trạng khô môi. Son lên chuẩn sắc và giữ màu đến 8 tiếng và có một lớp base hồng nhẹ giúp môi luôn có sức sống. Thiết kế thân vuông đặc trưng của thương hiệu Black Rouge với logo được in hologram óng ánh sang trọng.',
            quantityInStock:4,
            idCategory:1,
        },
        {
            idProduct: 26,
            productName: 'Kem Che Khuyết Điểm Black Rouge Zoom In HD Cover Fit Concealer Lâu Trôi 25.1g .#X1.7 Fair',
            productPrice:182000,
            productDescription:'Kem Che Khuyết Điểm Lâu Trôi Zoom In HD Cover Fit Concealer của Black Rouge với chất kem mỏng mịn, dễ tán. Che phủ hoàn hảo các khu vực nhiều khuyết điểm một cách nhanh chóng. Thân và nắp kem sử dụng chất liệu coating không bóng, màu đỏ ở nắp nổi bật và thu hút ánh nhìn.',
            quantityInStock:4,
            idCategory:2,
        },
        {
            idProduct: 27,
            productName: 'Bút Kẻ Mắt Nước Black Rouge Power Proof Chống Trôi 9.6g .#P01 Deep Black Màu Đen',
            productPrice:207000,
            productDescription:'Bút Kẻ Mắt Nước Black Rouge Power Proof Chống Trôi 9.6g thuộc bộ sưu tập Pool Party, cho nét kẻ thanh mảnh, chất gel nước cực kì sắc nét & khó lem, lên màu rõ ngay lần di bút đầu tiên.',
            quantityInStock:5,
            idCategory:3,
        },
        {
            idProduct: 28,
            productName: 'Son Kem Lì Black Rouge Cream Matt Rouge 26.5g .#CM09 Honeyed Cam Đất',
            productPrice:194000,
            productDescription:'Son kem lì Black Rouge Cream Matt Rouge II của Black Rouge trở lại với một phiên bản đặc biệt hơn, với 5 sắc son đồng hành cùng bạn qua mọi thời điểm. Sự kết hợp hai phong cách vừa hiện đại nhưng không kém phần cổ điển. Tôn lên từng khoảnh khắc rạng rỡ cho đôi môi của bạn.',
            quantityInStock:10,
            idCategory:1,
        },
        {
            idProduct: 29,
            productName: 'Bảng Phấn Mắt 4 Ô Black Rouge Crystal Heart Lock Shadow 37.5g .#CH03 Almond Coffret Nâu Beige',
            productPrice:260000,
            productDescription:'Bảng phấn mắt 4 màu đa công dụng Black Rouge Crystal Heart Lock Shadow quay lại với 2 bảng màu trung tính mới. Phù hợp cho mọi hoàn cảnh từ make up nhẹ nhàng đi học, đi chơi cho đến sắc sảo để dự các bữa tiệc.',
            quantityInStock:1,
            idCategory:3,
        },
        {
            idProduct: 30,
            productName: 'Chì Kẻ Mày Black Rouge Half-Hard Drawing Master Eyebrow 12.3g .#E01 Grey Master Nâu Xám',
            productPrice:156000,
            productDescription:'Chì kẻ mày Half-Hard Drawing Master Eyebrow của Black Rouge với thiết kế đầu chì hình tam giác giúp tạo dáng chân mày thật nhẹ nhàng, mang lại vẻ tự nhiên.Thiết kế đơn giản với chất liệu coating không bóng nhưng lại thể hiện sự hiện đại, sang trọng.',
            quantityInStock:1,
            idCategory:3,
        },
        {
            idProduct: 31,
            productName: 'Chì Kẻ Mày Black Rouge Half-Hard Drawing Master Eyebrow 12.3g .#E02 Brown Master Nâu Đen',
            productPrice:156000,
            productDescription:'Chì kẻ mày Half-Hard Drawing Master Eyebrow của Black Rouge với thiết kế đầu chì hình tam giác giúp tạo dáng chân mày thật nhẹ nhàng, mang lại vẻ tự nhiên.Thiết kế đơn giản với chất liệu coating không bóng nhưng lại thể hiện sự hiện đại, sang trọng.',
            quantityInStock:2,
            idCategory:3,
        },
        {
            idProduct: 32,
            productName: 'Son Thỏi Black Rouge Rose Velvet Lipstick Nhung Lì Mềm Mịn 24.5g .#R04 Burgundy Rose Đỏ Rượu',
            productPrice:207000,
            productDescription:'Son Thỏi Black Rouge Rose Velvet Lipstick Nhung Lì Mềm Mịn 24.5g nằm trong bộ sưu tập lấy cảm hứng từ hoa hồng - loài hoa thống trị cái đẹp. Rose Velvet Lipstick sở hữu cho mình chất son sáp mịn mượt nhẹ tênh cùng bảng màu đẹp đến khó cưỡng.',
            quantityInStock:5,
            idCategory:1,
        },
        {
            idProduct: 33,
            productName: 'Chì Kẻ Mày Black Rouge Half-Hard Drawing Master Eyebrow 12.3g .#E03 Ashe Master Nâu Sáng',
            productPrice:156000,
            productDescription:'Chì kẻ mày Half-Hard Drawing Master Eyebrow của Black Rouge với thiết kế đầu chì hình tam giác giúp tạo dáng chân mày thật nhẹ nhàng, mang lại vẻ tự nhiên.Thiết kế đơn giản với chất liệu coating không bóng nhưng lại thể hiện sự hiện đại, sang trọng.',
            quantityInStock:2,
            idCategory:3,
        },
        {
            idProduct: 34,
            productName: 'Son Kem Lì Black Rouge Mịn Môi AirFit Velvet Tint Ver 7 Velvet Crown 37.6g.#A36 Dust Pumpkin Cam Nâu',
            productPrice:209000,
            productDescription:'Sự trở lại của dòng son đình đám Velvet với một phiên bản đặc biệt, Air Fit Velvet Tint Ver 7 [Velvet Crown] sẽ đưa bạn đến vương quốc của sự quyến rũ khó cưỡng lại.',
            quantityInStock:1,
            idCategory:1,
        },
        {
            idProduct: 35,
            productName: 'Gel Nhũ Mắt Black Rouge Pearlvely I Glitter Universe Lấp Lánh 15.1g .#GU02 Iron Red Ánh Đỏ Nổi Bật',
            productPrice:207000,
            productDescription:'Với công thức Bling Bling độc quyền - tăng thêm hạt nhũ lớn cho hiệu ứng bắt sáng tối đa, khiến đôi mắt trở nên long lanh hơn bao giờ hết, bạn sẽ siêu cấp lung linh với phiên bản cực mới toanh từ Pearlvely I Glitter Universe.',
            quantityInStock:4,
            idCategory:3,
        },
        {
            idProduct: 36,
            productName: 'Son Kem Lì Black Rouge Mịn Môi AirFit Velvet Tint Ver 7 Velvet Crown 37.6g.#A37 Unrivaled Chili King',
            productPrice:209000,
            productDescription:'Sự trở lại của dòng son đình đám Velvet với một phiên bản đặc biệt, Air Fit Velvet Tint Ver 7 [Velvet Crown] sẽ đưa bạn đến vương quốc của sự quyến rũ khó cưỡng lại.',
            quantityInStock:6,
            idCategory:1,
        },
    ],
    productdetail: [
        {
            idProduct: 1,
            idImage: 1,
            image:"..//../image/Product/lips/lip1.jpg",
        },
        {
            idProduct: 2,
            idImage: 2,
            image: "..//../image/Product/lips/lip2.png",
        },
        {
            idProduct: 3,
            idImage: 3,
            image: "..//../image/Product/lips/lip3.png",
        },
        {
            idProduct: 4,
            idImage: 4,
            image: "..//../image/Product/lips/lip4.jpg",
        },
        {
            idProduct: 5,
            idImage: 5,
            image: "..//../image/Product/lips/lip5.jpg",
        },
        {
            idProduct: 6,
            idImage: 6,
            image: "..//../image/Product/eyes/eyes10.jpg",
        },
        {
            idProduct: 7,
            idImage: 7,
            image: "..//../image/Product/eyes/eyes8.png",
        },
        {
            idProduct: 8,
            idImage: 8,
            image: "..//../image/Product/eyes/eyes2.png",
        },
	    {
            idProduct: 9,
            idImage: 9,
            image: "..//../image/Product/face/face5.jpg",
        },
	    {
            idProduct: 10,
            idImage: 10,
            image: "..//../image/Product/eyes/eyes6.png",
        },
        {
            idProduct: 11,
            idImage: 11,
            image: "..//../image/Product/lips/lip11.jpg",
        },
	    {
            idProduct: 12,
            idImage: 12,
            image: "..//../image/Product/lips/lip12.jpg",
        },
	    {
            idProduct: 13,
            idImage: 13,
            image: "..//../image/Product/lips/lip13.jpg",
        },
        {
            idProduct: 14,
            idImage: 14,
            image: "..//../image/Product/lips/lip14.png",
        },
        {
            idProduct: 15,
            idImage: 15,
            image: "..//../image/Product/lips/lip15.png",
        },
        {
            idProduct: 16,
            idImage: 16,
            image: "..//../image/Product/lips/lip16.png",
        },
        {
            idProduct: 17,
            idImage: 17,
            image: "..//../image/Product/lips/lip17.png",
        },
        {
            idProduct: 18,
            idImage: 18,
            image: "..//../image/Product/lips/lip18.png",
        },
        {
            idProduct: 19,
            idImage: 19,
            image: "..//../image/Product/lips/lip19.png",
        },
        {
            idProduct: 20,
            idImage: 20,
            image: "..//../image/Product/lips/lip6.png",
        },
        {
            idProduct: 21,
            idImage: 21,
            image: "..//../image/Product/face/face1.png",
        },
        {
            idProduct: 22,
            idImage: 22,
            image: "..//../image/Product/face/face2.png",
        },
        {
            idProduct: 23,
            idImage: 23,
            image: "..//../image/Product/face/face3.jpg",
        },
        {
            idProduct: 24,
            idImage: 24,
            image: "..//../image/Product/face/face4.png",
        },
        {
            idProduct: 25,
            idImage: 25,
            image: "..//../image/Product/lips/lip7.png",
        },
        {
            idProduct: 26,
            idImage: 26,
            image: "..//../image/Product/face/face6.jpg",
        },
        {
            idProduct: 27,
            idImage: 27,
            image: "..//../image/Product/eyes/eyes1.png",
        },
        {
            idProduct: 28,
            idImage: 28,
            image: "..//../image/Product/lips/lip8.jpg",
        },
        {
            idProduct: 29,
            idImage: 29,
            image: "..//../image/Product/eyes/eyes3.png",
        },
        {
            idProduct: 30,
            idImage: 30,
            image: "..//../image/Product/eyes/eyes4.jpg",
        },
        {
            idProduct: 31,
            idImage: 31,
            image: "..//../image/Product/eyes/eyes5.jpg",
        },
        {
            idProduct: 32,
            idImage: 32,
            image: "..//../image/Product/lips/lip20.png",
        },
        {
            idProduct: 33,
            idImage: 33,
            image: "..//../image/Product/eyes/eyes7.png",
        },
        {
            idProduct: 34,
            idImage: 34,
            image: "..//../image/Product/lips/lip9.png",
        },
        {
            idProduct: 35,
            idImage: 35,
            image: "..//../image/Product/eyes/eyes9.png",
        },
        {
            idProduct: 36,
            idImage: 36,
            image: "..//../image/Product/lips/lip10.png",
        },
    ],
    categories:[
        {
            idCategory: 1,
            categoryName: 'Môi',
        },
        {
            idCategory:2,
            categoryName:'Mặt',
        },
        {
            idCategory:3,
            categoryName:'Mắt',
        }
    ]
};
 
  
  module.exports = data;